version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_database
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 0285
      POSTGRES_DB: my_database