CREATE USER juliam WITH PASSWORD '0285';
GRANT ALL PRIVILEGES ON DATABASE collegeconnect TO juliam;

CREATE USER thomask WITH PASSWORD '0285';
GRANT ALL PRIVILEGES ON DATABASE collegeconnect TO thomask;

CREATE USER jeromes WITH PASSWORD '0285';
GRANT ALL PRIVILEGES ON DATABASE collegeconnect TO jeromes;