version: '3'
services:
  postgres:
    build: 
      context: ./
      dockerfile: postgres.Dockerfile
    volumes:
      - ./collegeconnect.sql:/docker-entrypoint-initdb.d/collegeconnect.sql
      - ./createuser.sql:/docker-entrypoint-initdb.d/createuser.sql
    ports:
      - 54324:5432  #unique port num

  node:
    build: 
      context: ./
      dockerfile: node.Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000